# Generated by Django 4.2.30 on 2026-07-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stream_url', models.CharField(max_length=500)),
                ('speed_limit_kmh', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homography_matrix', models.JSONField()),
                ('reference_points', models.JSONField()),
                ('measured_distance_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calibrated_at', models.DateTimeField()),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_profile', to='cameras.camera')),
            ],
            options={
                'ordering': ['-calibrated_at'],
            },
        ),
    ]
