# Generated by Django 4.2.30 on 2026-07-13 16:11

import apps.infractions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anpr', '0001_initial'),
        ('cameras', '0001_initial'),
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_speed_kmh', models.DecimalField(decimal_places=1, max_digits=5)),
                ('speed_limit_kmh', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('detectee', 'Détectée'), ('verifiee', 'Vérifiée'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='detectee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infractions', to='cameras.camera')),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='infraction', to='detection.vehicledetection')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infractions', to='anpr.platereading')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_infractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInfraction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('recorded_speed_kmh', models.DecimalField(decimal_places=1, max_digits=5)),
                ('speed_limit_kmh', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('detectee', 'Détectée'), ('verifiee', 'Vérifiée'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='detectee', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('camera', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cameras.camera')),
                ('detection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='detection.vehicledetection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anpr.platereading')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical infraction',
                'verbose_name_plural': 'historical infractions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_image', models.ImageField(upload_to=apps.infractions.models.evidence_upload_path)),
                ('plate_crop_image', models.ImageField(blank=True, upload_to=apps.infractions.models.evidence_upload_path)),
                ('sha256_hash', models.CharField(editable=False, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='infractions.infraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
