# Generated by Django 4.2.30 on 2026-07-13 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infractions', '0002_agents_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraction',
            options={'ordering': ['-created_at'], 'permissions': [('verify_infraction', 'Peut vérifier une infraction détectée'), ('validate_infraction', 'Peut valider ou rejeter une infraction vérifiée')]},
        ),
        migrations.CreateModel(
            name='EvidenceAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_access_logs', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='infractions.evidence')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
