# Generated by Django 4.2.30 on 2026-07-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.PositiveIntegerField()),
                ('vehicle_class', models.CharField(choices=[('car', 'Voiture'), ('motorcycle', 'Moto / Zémidjan'), ('bus', 'Bus'), ('truck', 'Camion')], max_length=20)),
                ('zone_entered_at', models.DateTimeField()),
                ('zone_exited_at', models.DateTimeField()),
                ('computed_speed_kmh', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tracking_confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('bbox', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['camera', 'track_id'], name='detection_v_camera__d62c08_idx'), models.Index(fields=['created_at'], name='detection_v_created_f1d4d0_idx')],
            },
        ),
    ]
