# Generated by Django 4.2.30 on 2026-07-13 16:11

import apps.anpr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_plate', models.CharField(max_length=50)),
                ('normalized_plate', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('lisible', 'Lisible'), ('plaque_illisible', 'Plaque illisible')], max_length=20)),
                ('ocr_confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('plate_crop', models.ImageField(upload_to=apps.anpr.models.plate_crop_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_readings', to='detection.vehicledetection')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_plate_data', "Peut consulter les plaques d'immatriculation")],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlateReading',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('raw_plate', models.CharField(max_length=50)),
                ('normalized_plate', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('lisible', 'Lisible'), ('plaque_illisible', 'Plaque illisible')], max_length=20)),
                ('ocr_confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('plate_crop', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('detection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='detection.vehicledetection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plate reading',
                'verbose_name_plural': 'historical plate readings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
